### ISSUE TITLE
Python error during installation

### ISSUE THREAD

**Issue by 360fun** [gustavwilliam/macmoji#2]
Hi @gustavwilliam and thank you to have built this script, sadly I cannot make it working. 😿 
I'm on the latest version of **Mac OS Sonoma**, I followed your guide and installed the dependencies with **homebrew** without problems.

I've updated python:
`python3 --version
Python 3.9.6
`
`pip3 --version
pip 24.0 from /Users/.../Library/Python/3.9/lib/python/site-packages/pip (python 3.9)`

When I run the command `pip3 install macmoji` I get this error:

`Defaulting to user installation because normal site-packages is not writeable
ERROR: Ignored the following versions that require a different python version: 0.1.0 Requires-Python >=3.10,<4.0; 1.0.0 Requires-Python >=3.10,<4.0
ERROR: Could not find a version that satisfies the requirement macmoji (from versions: none)
ERROR: No matching distribution found for macmoji`

I've also tried, as suggested by people with similar issue, to run `python3 -m pip install macmoji` but with the same result. 😢

**Comment by gustavwilliam** [comment]
Hi! If I'm interpreting this error message correctly, it seems like you're using Python 3.9, while the package requires 3.10. Hopefully if it works if you update!

I'll add a note in the README.md to clarify this for people trying to install it in the future 😄

**Comment by 360fun** [comment]
Oh yeah, I realised that the version was updated but it was using the old one. Now I managed to install it, thanks!
